#!/usr/bin/env bash
set -euo pipefail

echo "Access the web UI here:"
echo

for ctr in prometheus cadvisor
do
  container_name_prefix="${PROJECT_NAME}-${SERVICE_NAME}-${ctr}"
  container_id=$(docker ps --filter name="$container_name_prefix" --format {{.ID}})
  if [ -z "$container_id" ]
  then
    echo >&2 "Error: Cannot find $SERVICE_NAME container ($container_name_prefix)."
    exit 1
  fi

  hostport=$(docker ps --filter="name=$container_name_prefix" --format {{.Ports}} | cut -f1 -d-)
  echo "    $ctr: http://$hostport"
done

echo

