version: "3.9"

services:
  prometheus:
    container_name: ${PROJECT_NAME}-${SERVICE_NAME}-prometheus
    hostname: ${SERVICE_NAME}-prometheus
    image: prom/prometheus:latest
    ports:
      - 127.0.0.1:0:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - .rp/${SERVICE_NAME}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus
    depends_on:
      - cadvisor

  cadvisor:
    container_name: ${PROJECT_NAME}-${SERVICE_NAME}-cadvisor
    hostname: ${SERVICE_NAME}-cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 127.0.0.1:0:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  prometheus:
    name: ${PROJECT_NAME}-${SERVICE_NAME}-prometheus
