version: "3.9"
services:
  superset:
    container_name: ${PROJECT_NAME}-${SERVICE_NAME}-superset
    hostname: ${SERVICE_NAME}-superset
    build:
      context: .rp/${SERVICE_NAME}/build
    logging:
      driver: "none"
    ports:
      - 127.0.0.1:0:8088
    restart: unless-stopped
    volumes:
      - type: volume
        source: superset_docker
        target: /app/docker
      - type: volume
        source: superset_home
        target: /app/superset_home

volumes:
  superset_docker:
  superset_home:

